<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="MR_ENUM" nsPrefix="MR_ENUM" nsURI="http://MR_ENUM/1.0">
	<eClassifiers xsi:type="ecore:EEnum" name="AccumulationKind">
		<eLiterals name="none" value="0"/>
		<eLiterals name="bulkQuantity" value="1"/>
		<eLiterals name="continuousCumulative" value="2"/>
		<eLiterals name="cumulative" value="3"/>
		<eLiterals name="deltaData" value="4"/>
		<eLiterals name="indicating" value="6"/>
		<eLiterals name="summation" value="9"/>
		<eLiterals name="timeDelay" value="10"/>
		<eLiterals name="instantaneous" value="12"/>
		<eLiterals name="latchingQuantity" value="13"/>
		<eLiterals name="boundedQuantity" value="14"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="AggregateKind">
		<eLiterals name="none" value="0"/>
		<eLiterals name="average" value="2"/>
		<eLiterals name="excess" value="4"/>
		<eLiterals name="highThreshold" value="5"/>
		<eLiterals name="lowThreshold" value="7"/>
		<eLiterals name="maximum" value="8"/>
		<eLiterals name="minimum" value="9"/>
		<eLiterals name="nominal" value="11"/>
		<eLiterals name="normal" value="12"/>
		<eLiterals name="secondMaximum" value="16"/>
		<eLiterals name="secondMinimum" value="17"/>
		<eLiterals name="thirdMaximum" value="23"/>
		<eLiterals name="fourthMaximum" value="24"/>
		<eLiterals name="fifthMaximum" value="25"/>
		<eLiterals name="sum" value="26"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="AmiBillingReadyKind">
		<eLiterals name="enabled" value=""/>
		<eLiterals name="operable" value=""/>
		<eLiterals name="billingApproved" value=""/>
		<eLiterals name="nonAmi" value=""/>
		<eLiterals name="amiDisabled" value=""/>
		<eLiterals name="amiCapable" value=""/>
		<eLiterals name="nonMetered" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="ComDirectionKind">
		<eLiterals name="fromDevice" value=""/>
		<eLiterals name="toDevice" value=""/>
		<eLiterals name="biDirectional" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="ComTechnologyKind">
		<eLiterals name="cellular" value=""/>
		<eLiterals name="ethernet" value=""/>
		<eLiterals name="homePlug" value=""/>
		<eLiterals name="pager" value=""/>
		<eLiterals name="phone" value=""/>
		<eLiterals name="plc" value=""/>
		<eLiterals name="rf" value=""/>
		<eLiterals name="rfMesh" value=""/>
		<eLiterals name="zigbee" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="CommodityKind">
		<eLiterals name="none" value="0"/>
		<eLiterals name="electricitySecondaryMetered" value="1"/>
		<eLiterals name="electricityPrimaryMetered" value="2"/>
		<eLiterals name="communication" value="3"/>
		<eLiterals name="air" value="4"/>
		<eLiterals name="insulativeGas" value="5"/>
		<eLiterals name="insulativeOil" value="6"/>
		<eLiterals name="naturalGas" value="7"/>
		<eLiterals name="propane" value="8"/>
		<eLiterals name="potableWater" value="9"/>
		<eLiterals name="steam" value="10"/>
		<eLiterals name="wasteWater" value="11"/>
		<eLiterals name="heatingFluid" value="12"/>
		<eLiterals name="coolingFluid" value="13"/>
		<eLiterals name="nonpotableWater" value="14"/>
		<eLiterals name="nox" value="15"/>
		<eLiterals name="so2" value="16"/>
		<eLiterals name="ch4" value="17"/>
		<eLiterals name="co2" value="18"/>
		<eLiterals name="carbon" value="19"/>
		<eLiterals name="hch" value="20"/>
		<eLiterals name="pfc" value="21"/>
		<eLiterals name="sf6" value="22"/>
		<eLiterals name="tvLicence" value="23"/>
		<eLiterals name="internet" value="24"/>
		<eLiterals name="refuse" value="25"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="EndDeviceFunctionKind">
		<eLiterals name="reverseFlow" value=""/>
		<eLiterals name="demandResponse" value=""/>
		<eLiterals name="metrology" value=""/>
		<eLiterals name="outageHistory" value=""/>
		<eLiterals name="relaysProgramming" value=""/>
		<eLiterals name="onRequestRead" value=""/>
		<eLiterals name="autonomousDst" value=""/>
		<eLiterals name="electricMetering" value=""/>
		<eLiterals name="gasMetering" value=""/>
		<eLiterals name="waterMetering" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="FlowDirectionKind">
		<eLiterals name="none" value="0"/>
		<eLiterals name="forward" value="1"/>
		<eLiterals name="lagging" value="2"/>
		<eLiterals name="leading" value="3"/>
		<eLiterals name="net" value="4"/>
		<eLiterals name="q1plusQ2" value="5"/>
		<eLiterals name="q1plusQ3" value="7"/>
		<eLiterals name="q1plusQ4" value="8"/>
		<eLiterals name="q1minusQ4" value="9"/>
		<eLiterals name="q2plusQ3" value="10"/>
		<eLiterals name="q2plusQ4" value="11"/>
		<eLiterals name="q2minusQ3" value="12"/>
		<eLiterals name="q3plusQ4" value="13"/>
		<eLiterals name="q3minusQ2" value="14"/>
		<eLiterals name="quadrant1" value="15"/>
		<eLiterals name="quadrant2" value="16"/>
		<eLiterals name="quadrant3" value="17"/>
		<eLiterals name="quadrant4" value="18"/>
		<eLiterals name="reverse" value="19"/>
		<eLiterals name="total" value="20"/>
		<eLiterals name="totalByPhase" value="21"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="MacroPeriodKind">
		<eLiterals name="none" value="0"/>
		<eLiterals name="billingPeriod" value="8"/>
		<eLiterals name="daily" value="11"/>
		<eLiterals name="monthly" value="13"/>
		<eLiterals name="seasonal" value="22"/>
		<eLiterals name="weekly" value="24"/>
		<eLiterals name="specifiedPeriod" value="32"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="MeasurementKind">
		<eLiterals name="none" value="0"/>
		<eLiterals name="apparentPowerFactor" value="2"/>
		<eLiterals name="currency" value="3"/>
		<eLiterals name="current" value="4"/>
		<eLiterals name="currentAngle" value="5"/>
		<eLiterals name="currentImbalance" value="6"/>
		<eLiterals name="date" value="7"/>
		<eLiterals name="demand" value="8"/>
		<eLiterals name="distance" value="9"/>
		<eLiterals name="distortionVoltAmp" value="10"/>
		<eLiterals name="energization" value="11"/>
		<eLiterals name="energy" value="12"/>
		<eLiterals name="energizationLoadSide" value="13"/>
		<eLiterals name="fan" value="14"/>
		<eLiterals name="frequency" value="15"/>
		<eLiterals name="fund" value="16"/>
		<eLiterals name="ieee1366ASAI" value="17"/>
		<eLiterals name="ieee1366ASIDI" value="18"/>
		<eLiterals name="ieee1366ASIFI" value="19"/>
		<eLiterals name="ieee1366CAIDI" value="20"/>
		<eLiterals name="ieee1366CAIFI" value="21"/>
		<eLiterals name="ieee1366CEMIn" value="22"/>
		<eLiterals name="ieee1366CEMSMIn" value="23"/>
		<eLiterals name="ieee1366CTAIDI" value="24"/>
		<eLiterals name="ieee1366MAIFI" value="25"/>
		<eLiterals name="ieee1366MAIFIe" value="26"/>
		<eLiterals name="ieee1366SAIDI" value="27"/>
		<eLiterals name="ieee1366SAIFI" value="28"/>
		<eLiterals name="lineLoss" value="31"/>
		<eLiterals name="loss" value="32"/>
		<eLiterals name="negativeSequence" value="33"/>
		<eLiterals name="phasorPowerFactor" value="34"/>
		<eLiterals name="phasorReactivePower" value="35"/>
		<eLiterals name="positiveSequence" value="36"/>
		<eLiterals name="power" value="37"/>
		<eLiterals name="powerFactor" value="38"/>
		<eLiterals name="quantityPower" value="40"/>
		<eLiterals name="sag" value="41"/>
		<eLiterals name="swell" value="42"/>
		<eLiterals name="switchPosition" value="43"/>
		<eLiterals name="tapPosition" value="44"/>
		<eLiterals name="tariffRate" value="45"/>
		<eLiterals name="temperature" value="46"/>
		<eLiterals name="totalHarmonicDistortion" value="47"/>
		<eLiterals name="transformerLoss" value="48"/>
		<eLiterals name="unipedeVoltageDip10to15" value="49"/>
		<eLiterals name="unipedeVoltageDip15to30" value="50"/>
		<eLiterals name="unipedeVoltageDip30to60" value="51"/>
		<eLiterals name="unipedeVoltageDip60to90" value="52"/>
		<eLiterals name="unipedeVoltageDip90to100" value="53"/>
		<eLiterals name="voltage" value="54"/>
		<eLiterals name="voltageAngle" value="55"/>
		<eLiterals name="voltageExcursion" value="56"/>
		<eLiterals name="voltageImbalance" value="57"/>
		<eLiterals name="volume" value="58"/>
		<eLiterals name="zeroFlowDuration" value="59"/>
		<eLiterals name="zeroSequence" value="60"/>
		<eLiterals name="distortionPowerFactor" value="64"/>
		<eLiterals name="frequencyExcursion" value="81"/>
		<eLiterals name="applicationContext" value="90"/>
		<eLiterals name="apTitle" value="91"/>
		<eLiterals name="assetNumber" value="92"/>
		<eLiterals name="bandwidth" value="93"/>
		<eLiterals name="batteryVoltage" value="94"/>
		<eLiterals name="broadcastAddress" value="95"/>
		<eLiterals name="deviceAddressType1" value="96"/>
		<eLiterals name="deviceAddressType2" value="97"/>
		<eLiterals name="deviceAddressType3" value="98"/>
		<eLiterals name="deviceAddressType4" value="99"/>
		<eLiterals name="deviceClass" value="100"/>
		<eLiterals name="electronicSerialNumber" value="101"/>
		<eLiterals name="endDeviceID" value="102"/>
		<eLiterals name="groupAddressType1" value="103"/>
		<eLiterals name="groupAddressType2" value="104"/>
		<eLiterals name="groupAddressType3" value="105"/>
		<eLiterals name="groupAddressType4" value="106"/>
		<eLiterals name="ipAddress" value="107"/>
		<eLiterals name="macAddress" value="108"/>
		<eLiterals name="mfgAssignedConfigurationID" value="109"/>
		<eLiterals name="mfgAssignedPhysicalSerialNumber" value="110"/>
		<eLiterals name="mfgAssignedProductNumber" value="111"/>
		<eLiterals name="mfgAssignedUniqueCommunicationAddress" value="112"/>
		<eLiterals name="multiCastAddress" value="113"/>
		<eLiterals name="oneWayAddress" value="114"/>
		<eLiterals name="signalStrength" value="115"/>
		<eLiterals name="twoWayAddress" value="116"/>
		<eLiterals name="signaltoNoiseRatio" value="117"/>
		<eLiterals name="alarm" value="118"/>
		<eLiterals name="batteryCarryover" value="119"/>
		<eLiterals name="dataOverflowAlarm" value="120"/>
		<eLiterals name="demandLimit" value="121"/>
		<eLiterals name="demandReset" value="122"/>
		<eLiterals name="diagnostic" value="123"/>
		<eLiterals name="emergencyLimit" value="124"/>
		<eLiterals name="encoderTamper" value="125"/>
		<eLiterals name="ieee1366MomentaryInterruption" value="126"/>
		<eLiterals name="ieee1366MomentaryInterruptionEvent" value="127"/>
		<eLiterals name="ieee1366SustainedInterruption" value="128"/>
		<eLiterals name="interruptionBehaviour" value="129"/>
		<eLiterals name="inversionTamper" value="130"/>
		<eLiterals name="loadInterrupt" value="131"/>
		<eLiterals name="loadShed" value="132"/>
		<eLiterals name="maintenance" value="133"/>
		<eLiterals name="physicalTamper" value="134"/>
		<eLiterals name="powerLossTamper" value="135"/>
		<eLiterals name="powerOutage" value="136"/>
		<eLiterals name="powerQuality" value="137"/>
		<eLiterals name="powerRestoration" value="138"/>
		<eLiterals name="programmed" value="139"/>
		<eLiterals name="pushbutton" value="140"/>
		<eLiterals name="relayActivation" value="141"/>
		<eLiterals name="relayCycle" value="142"/>
		<eLiterals name="removalTamper" value="143"/>
		<eLiterals name="reprogrammingTamper" value="144"/>
		<eLiterals name="reverseRotationTamper" value="145"/>
		<eLiterals name="switchArmed" value="146"/>
		<eLiterals name="switchDisabled" value="147"/>
		<eLiterals name="tamper" value="148"/>
		<eLiterals name="watchdogTimeout" value="149"/>
		<eLiterals name="billLastPeriod" value="150"/>
		<eLiterals name="billToDate" value="151"/>
		<eLiterals name="billCarryover" value="152"/>
		<eLiterals name="connectionFee" value="153"/>
		<eLiterals name="audibleVolume" value="154"/>
		<eLiterals name="volumetricFlow" value="155"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="MeasuringPeriodKind">
		<eLiterals name="none" value="0"/>
		<eLiterals name="tenMinute" value="1"/>
		<eLiterals name="fifteenMinute" value="2"/>
		<eLiterals name="oneMinute" value="3"/>
		<eLiterals name="twentyfourHour" value="4"/>
		<eLiterals name="thirtyMinute" value="5"/>
		<eLiterals name="fiveMinute" value="6"/>
		<eLiterals name="sixtyMinute" value="7"/>
		<eLiterals name="twoMinute" value="10"/>
		<eLiterals name="threeMinute" value="14"/>
		<eLiterals name="present" value="15"/>
		<eLiterals name="previous" value="16"/>
		<eLiterals name="twentyMinute" value="31"/>
		<eLiterals name="fixedBlock60Min" value="50"/>
		<eLiterals name="fixedBlock30Min" value="51"/>
		<eLiterals name="fixedBlock20Min" value="52"/>
		<eLiterals name="fixedBlock15Min" value="53"/>
		<eLiterals name="fixedBlock10Min" value="54"/>
		<eLiterals name="fixedBlock5Min" value="55"/>
		<eLiterals name="fixedBlock1Min" value="56"/>
		<eLiterals name="rollingBlock60MinIntvl30MinSubIntvl" value="57"/>
		<eLiterals name="rollingBlock60MinIntvl20MinSubIntvl" value="58"/>
		<eLiterals name="rollingBlock60MinIntvl15MinSubIntvl" value="59"/>
		<eLiterals name="rollingBlock60MinIntvl12MinSubIntvl" value="60"/>
		<eLiterals name="rollingBlock60MinIntvl10MinSubIntvl" value="61"/>
		<eLiterals name="rollingBlock60MinIntvl6MinSubIntvl" value="62"/>
		<eLiterals name="rollingBlock60MinIntvl5MinSubIntvl" value="63"/>
		<eLiterals name="rollingBlock60MinIntvl4MinSubIntvl" value="64"/>
		<eLiterals name="rollingBlock30MinIntvl15MinSubIntvl" value="65"/>
		<eLiterals name="rollingBlock30MinIntvl10MinSubIntvl" value="66"/>
		<eLiterals name="rollingBlock30MinIntvl6MinSubIntvl" value="67"/>
		<eLiterals name="rollingBlock30MinIntvl5MinSubIntvl" value="68"/>
		<eLiterals name="rollingBlock30MinIntvl3MinSubIntvl" value="69"/>
		<eLiterals name="rollingBlock30MinIntvl2MinSubIntvl" value="70"/>
		<eLiterals name="rollingBlock15MinIntvl5MinSubIntvl" value="71"/>
		<eLiterals name="rollingBlock15MinIntvl3MinSubIntvl" value="72"/>
		<eLiterals name="rollingBlock15MinIntvl1MinSubIntvl" value="73"/>
		<eLiterals name="rollingBlock10MinIntvl5MinSubIntvl" value="74"/>
		<eLiterals name="rollingBlock10MinIntvl2MinSubIntvl" value="75"/>
		<eLiterals name="rollingBlock10MinIntvl1MinSubIntvl" value="76"/>
		<eLiterals name="rollingBlock5MinIntvl1MinSubIntvl" value="77"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="MeterMultiplierKind">
		<eLiterals name="kH" value=""/>
		<eLiterals name="kR" value=""/>
		<eLiterals name="kE" value=""/>
		<eLiterals name="ctRatio" value=""/>
		<eLiterals name="ptRatio" value=""/>
		<eLiterals name="transformerRatio" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="RandomisationKind">
		<eLiterals name="start" value=""/>
		<eLiterals name="end" value=""/>
		<eLiterals name="startAndEnd" value=""/>
		<eLiterals name="default" value=""/>
		<eLiterals name="none" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="ReadingReasonKind">
		<eLiterals name="installation" value=""/>
		<eLiterals name="removal" value=""/>
		<eLiterals name="inquiry" value=""/>
		<eLiterals name="billing" value=""/>
		<eLiterals name="moveIn" value=""/>
		<eLiterals name="moveOut" value=""/>
		<eLiterals name="demandReset" value=""/>
		<eLiterals name="serviceDisconnect" value=""/>
		<eLiterals name="serviceConnect" value=""/>
		<eLiterals name="loadManagement" value=""/>
		<eLiterals name="loadResearch" value=""/>
		<eLiterals name="other" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="ServiceMultiplierKind">
		<eLiterals name="ctRatio" value=""/>
		<eLiterals name="ptRatio" value=""/>
		<eLiterals name="transformerRatio" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="TransmissionModeKind">
		<eLiterals name="normal" value=""/>
		<eLiterals name="anonymous" value=""/>
		<eLiterals name="both" value=""/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EEnum" name="UsagePointConnectedKind">
		<eLiterals name="connected" value=""/>
		<eLiterals name="physicallyDisconnected" value=""/>
		<eLiterals name="logicallyDisconnected" value=""/>
	</eClassifiers>
</ecore:EPackage>
